//Products endpoints

GET http://localhost:3306/products
Content-Type: application/json

###
GET http://localhost:3306/products/1674491518624
Content-Type: application/json

###
POST http://localhost:3306/products
Content-Type: application/json

{
    "name": "Volleyball Uniform",
    "category": "Sporty",
    "quantity": 30,
    "price": 99.99
}

###
PATCH http://localhost:3306/products/1674491518624
Content-Type: application/json

{
    "name": "Handball Ball",
    "category": "Sporty",
    "quantity": 48,
    "price": 85.99
}

###
PUT http://localhost:3306/products/1674491611616
Content-Type: application/json

//Customers endpoints

###
GET http://localhost:3306/customers
Content-Type: application/json

###
GET http://localhost:3306/customers/1674481805685
Content-Type: application/json

###
POST http://localhost:3306/customers
Content-Type: application/json

{
    "fullName": "Maria Rodrigues",
    "cpf": "821.475.406-25",
    "email": "maria@gmail.com",
    "birthDate": "1975-10-10"
}

###
PATCH http://localhost:3306/customers/1674481805685
Content-Type: application/json

{
    "fullName": "Giovana Vieira",
    "email": "gioivieira@outlook.com"
}

###
PUT http://localhost:3306/customers/1674481805685
Content-Type: application/json

//Orders endpoints

###
GET http://localhost:3306/orders
Content-Type: application/json

###
GET http://localhost:3306/orders/1674491909467
Content-Type: application/json

###
POST http://localhost:3306/orders
Content-Type: application/json

{
    "productId": "1674491518624",
    "customerId": "1674481805685",
    "quantity": 2
}

###
DELETE http://localhost:3306/orders/1674491775208
Content-Type: application/json

//API IBGE

###
GET http://localhost:3306/counties
Content-Type: application/json

###
POST http://localhost:3306/counties
Content-Type: application/json