//Products endpoints

GET http://localhost:3306/products
Content-Type: application/json

###
GET http://localhost:3306/products/1674481988053
Content-Type: application/json

###
POST http://localhost:3306/products
Content-Type: application/json

{
    "name": "Bola Futsal",
    "category": "Esportivo",
    "price": 59.99,
    "quantity": 70
}

###
PATCH http://localhost:3306/products/1674481988053
Content-Type: application/json

{
    "name": "Bola Handebol",
    "category": "Esportivo",
    "quantity": 25,
    "price": 45.99
}

###
PUT http://localhost:3306/products/1674481988053
Content-Type: application/json

//Customers endpoints

###
GET http://localhost:3306/customers
Content-Type: application/json

###
GET http://localhost:3306/customers/1674481805685
Content-Type: application/json

###
POST http://localhost:3306/customers
Content-Type: application/json

{
    "fullName": "Maria Rodrigues",
    "cpf": "821.475.406-25",
    "email": "maria@gmail.com",
    "birthDate": "1975-10-10"
}

###
PATCH http://localhost:3306/customers/1674481805685
Content-Type: application/json

{
    "fullName": "Giovana Vieira",
    "email": "gioivieira@outlook.com"
}

###
PUT http://localhost:3306/customers/1674481805685
Content-Type: application/json

//Orders endpoints

###
GET http://localhost:3306/orders
Content-Type: application/json

###
GET http://localhost:3306/orders/1674312696764
Content-Type: application/json

###
POST http://localhost:3306/orders
Content-Type: application/json

{
    "productId": "1674480445880",
    "customerId": "1674480478444",
    "quantity": 2
}

###
DELETE http://localhost:3306/orders/1674312696764
Content-Type: application/json

//API IBGE

###
GET http://localhost:3306/counties
Content-Type: application/json

###
POST http://localhost:3306/counties
Content-Type: application/json